author: Callum McColl
theme: fullwidth

exclude:
    - Sources/*/gu_*.swift

custom_categories:
    - name: Nao
      children: 
          - NaoV5
          - NaoWBIndexes
          - NaoJointsContainer
          - NaoJoints
          - NaoHead
          - NaoHeadSensors
          - NaoArm
          - NaoHandSensors
          - NaoLeg
          - ManageableNaoV5

    - name: Robot Types
      children:
          - NaoRobot
          - SoccerPlayingRobot
          - UpdateableRobot

    - name: Cameras
      children:
          - BottomCameraContainer
          - BottomCameraPivotContainer
          - CameraPivotContainer
          - TopCameraContainer
          - TopCameraPivotContainer

    - name: Joints
      children:
          - JointsContainer
          - PitchJoint
          - PitchRollJoint
          - PitchYawJoint
          - YPJoint
          - YawJoint
          - YawRollJoint

    - name: Player Data
      children:
          - PlayerNumberContainer

    - name: Locations
      children:
          - SoccerObjectLocationsContainer
          - SoccerObjectLocations

    - name: Localisation
      children:
          - FieldPositionContainer
          - BallPositionContainer
          - BallPosition
          - Orientation

    - name: Converting C Types
      children:
          - CTypeDelegator
          - CTypeWrapper
