author: Callum McColl
theme: fullwidth

exclude:
    - Sources/*/gu_*.swift
    - Sources/GURobots/HorizonSighting+Codable.swift
    - gu_util/*
    - guunits/*
    - gucoordinates/*
    - guvision_utils/*
    - gusimplewhiteboard/*
    - gurobots/*

custom_categories:
    - name: Nao
      children: 
          - NaoV5
          - NaoWBIndexes
          - NaoJointsContainer
          - NaoJoints
          - NaoHead
          - NaoHeadSensors
          - NaoArm
          - NaoHandSensors
          - NaoLeg
          - ManageableNaoV5

    - name: Robot Types
      children:
          - NaoRobot
          - SoccerPlayingRobot
          - UpdateableRobot

    - name: Player Data
      children:
          - PlayerNumberContainer

    - name: Cameras
      children:
          - RobotCamera
          - CamerasContainer
          - BottomCameraContainer
          - BottomCameraIndexContainer
          - TopCameraContainer
          - TopCameraIndexContainer

    - name: Joints
      children:
          - JointsContainer
          - PitchJoint
          - PitchRollJoint
          - PitchYawJoint
          - YPJoint
          - YawJoint
          - YawRollJoint

    - name: Sightings (Vision)
      children:
          - SoccerSightingsContainer
          - BottomCameraSoccerSightingsContainer
          - TopCameraSoccerSightingsContainer
          - SoccerSightings
          - EllipseSighting
          - RectangleSighting
          - HorizonSighting
          - CornerSighting
          - LineSighting

    - name: Locations
      children:
          - SoccerObjectLocationsContainer
          - SoccerObjectLocations

    - name: Localisation
      children:
          - FieldPositionContainer
          - BallPositionContainer
          - BallPosition
          - Orientation

    - name: Converting C Types
      children:
          - CTypeDelegator
          - CTypeWrapper
