name: Jazzy Documentation

on:
  push:
    branches: [ main ]

jobs:

  exec-jazzy:
    runs-on: macos-11

    steps:
    - name: Install Ninja
      run: brew install ninja

    - name: Clone gu_util
      uses: actions/checkout@v2
      with:
        repository: mipalgu/gu_util
        path: gu_util

    - name: Install gu_util
      run: |
        cd gu_util
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja
        ninja install
        cd ../..

    - name: Clone guunits
      uses: actions/checkout@v2
      with:
        repository: mipalgu/guunits
        path: guunits

    - name: Install guunits
      run: |
        cd guunits/guunits
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja
        ninja install
        cd ../../..
    
    - name: Clone gucoordinates
      uses: actions/checkout@v2
      with:
        repository: mipalgu/gucoordinates
        path: gucoordinates

    - name: Install gucoordinates
      run: |
        cd gucoordinates/gucoordinates
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja
        ninja install
        cd ../../..

    - name: Clone SimpleShapes
      uses: actions/checkout@v2
      with:
        repository: mipalgu/SimpleShapes
        path: SimpleShapes

    - name: Install SimpleShapes
      run: |
        cd SimpleShapes
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja
        ninja install
        cd ../..

    - name: Clone gusimplewhiteboard
      uses: actions/checkout@v2
      with:
        repository: mipalgu/gusimplewhiteboard
        path: gusimplewhiteboard

    - name: Install gusimplewhiteboard
      run: |
        cd gusimplewhiteboard
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja
        ninja install
        cd ../..

    - name: Clone Repository 
      uses: actions/checkout@v2
      with:
        repository: mipalgu/swift_GURobots
        path: swift_GURobots

    - name: Copy Readme.md and .jazzy.yaml
      run: |
        cp swift_GURobots/README.md .
        cp swift_GURobots/.jazzy.yaml .

    - name: Jazzy Action
      uses: sersoft-gmbh/swifty-docs-action@v1.2.0
      with:
        source: ${{github.workspace}}/swift_GURobots
        output: docs

    - name: Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
